Fix Hadoop 3.x MRAppMaster ClassNotFoundException in pseudo mode
YARN containers do not inherit HADOOP_HOME, causing the MR
ApplicationMaster JVM to fail with:
  ClassNotFoundException: org.apache.hadoop.mapreduce.v2.app.MRAppMaster

Fix by setting HADOOP_MAPRED_HOME for AM, map, and reduce containers.